services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    environment:
      - POSTGRES_DB=SVN
      - POSTGRES_USER=SVN_Admin
      - POSTGRES_PASSWORD=SVN_logistics_2022
    depends_on:
      - db
  db:
    image: postgres:14.8
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    expose:
      - 5432:5432
    environment:
      - POSTGRES_DB=SVN
      - POSTGRES_USER=SVN_Admin
      - POSTGRES_PASSWORD=SVN_logistics_2022
volumes:
  postgres_data: